# app/config/config_prod.yml
monolog:
  # ...
  handlers:
    nested:
      type: error_log
imports:
  - { resource: config.yml }
  - { resource: config_prod_secrets.php }

# ..
framework:
  session:
    # set handler_id to null to use default session handler from php.ini (memcached)
    handler_id:  ~